import { expect, test } from 'playwright/test'

for (const viewport of [{ width: 320, height: 568 }, { width: 390, height: 844 }, { width: 844, height: 390 }, { width: 1280, height: 720 }]) {
  test('bedside controls stay accessible at ' + viewport.width + 'x' + viewport.height, async ({ page }) => {
    await page.setViewportSize(viewport)
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/')
    await expect(page.locator('html')).toHaveAttribute('data-tqw-booted', '1', { timeout: 30_000 })
    const essentials = page.locator('.dock-essentials')
    for (const name of ['Toggle clock', 'Enable nighttime sound', 'More settings']) {
      const button = essentials.getByRole('button', { name, exact: true })
      await expect(button).toBeInViewport({ ratio: 1 })
      const box = await button.boundingBox()
      expect(box!.width).toBeGreaterThanOrEqual(44)
      expect(box!.height).toBeGreaterThanOrEqual(44)
    }
    await page.getByRole('button', { name: 'More settings', exact: true }).click()
    await expect(page.locator('.first-visit-whisper')).toBeHidden()
    await page.getByRole('button', { name: /Sleep timer Fade/ }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: 'Start timer', exact: true }).click()
    await page.getByRole('button', { name: 'More settings', exact: true }).click()
    await page.getByRole('button', { name: /Sleep timer Fade/ }).click()
    await expect(page.getByRole('button', { name: 'Cancel timer', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('button', { name: 'Rain scene', exact: true }).focus()
    await expect(page.getByRole('button', { name: 'Rain scene', exact: true })).toBeInViewport({ ratio: 1 })
    await expect(essentials.getByRole('button', { name: 'More settings', exact: true })).toBeInViewport({ ratio: 1 })
    expect(errors).toEqual([])
  })
}

test('sunrise preview finishes, can be stopped, and refresh cancels an armed alarm', async ({ page }) => {
  const clockTime = new Date()
  await page.clock.install({ time: clockTime })
  await page.clock.pauseAt(new Date(clockTime.getTime() + 1_000))
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('data-tqw-booted', '1', { timeout: 30_000 })
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await page.getByRole('button', { name: /Sunrise alarm Wake/ }).click()
  await expect(page.getByRole('dialog')).toContainText('Refreshing or closing this page cancels the alarm.')
  const volume = page.getByRole('slider', { name: 'Wake-up sound level' })
  await volume.fill('0')
  await page.getByRole('button', { name: 'Preview sunrise', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Sunrise preview' })).toBeVisible()
  await page.clock.fastForward(24_100)
  await expect(page.getByRole('region', { name: 'Sunrise preview' })).toContainText('Returning to night')
  await page.clock.fastForward(2_100)
  await expect(page.getByRole('region', { name: 'Sunrise preview' })).toHaveCount(0)
  await page.mouse.move(30, 30)
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await page.getByRole('button', { name: /Sunrise alarm Wake/ }).click()
  await page.getByRole('button', { name: 'Preview sunrise', exact: true }).click()
  await page.getByRole('button', { name: 'End preview', exact: true }).click()
  await page.clock.fastForward(2_100)
  await expect(page.getByRole('region', { name: 'Sunrise preview' })).toHaveCount(0)
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await page.getByRole('button', { name: /Sunrise alarm Wake/ }).click()
  await page.getByRole('button', { name: 'Arm sunrise', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Sunrise armed')
  await page.reload()
  await page.getByRole('button', { name: 'More settings', exact: true }).click()
  await expect(page.getByRole('button', { name: /Sunrise alarm Wake/ })).toContainText('Off')
})
